import "./globals.css";
import { figtree, jetBrainsMono } from "@/components/fonts";
import { ThemeProvider } from "@/components/ui/theme/theme-provider";
import { Metadata } from "next";

export const metadata: Metadata = {
	title: {
		template: "%s | Gitback by Salman",
		default: "Gitback by Salman"
	},
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${figtree.className} ${jetBrainsMono.className} antialiased`}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
